# version: '3.3'
version: "2"
services:
  django:
    build:
      context: ./docker
      dockerfile: Backend.Dockerfile
    container_name: django-backend
    environment:
      TZ: "Asia/Taipei"
    command: sh -c "cd /app/backend && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    networks:
      - internal
#  vue:
#    build:
#      context: .
#      dockerfile: docker/FrontendDockerfile
#    container_name: django-vue-frontend
#    volumes:
#      - .:/app
#    ports:
#      - "8082:8080"
#    depends_on:
#      - django
#    networks:
#      - internal
networks:
  internal:
    driver: bridge