# version: '3.3'
version: "3"
services:
  vue-app:
    build:
      context: .
      dockerfile: docker/FrontendDockerfile
    container_name: django-vue-frontend
    volumes:
      - .:/app
      - /app/node_modules
    # ports:
    #   - "8082:8080"
    ports:
        - "8080:8080"
    depends_on:
      - django
    networks:
      - internal
    environment:
      - NODE_ENV=development