version: '3.3'

services:
  db:
    restart: always
    image: mysql:5.7.42
    container_name: mysql
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: "99s6HiMn5ytBkE0a"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "Uybkpu0C62"
      TZ: "Asia/Taipei"
    volumes:
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
  django:
    restart: always
    build:
      context: .
      dockerfile: docker/BackendDockerfile
    container_name: django-vue-backend
    command: ./docker/backend_setup.sh
    environment:
      MYSQL_ROOT_PASSWORD: "99s6HiMn5ytBkE0a"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "Uybkpu0C62"
      TZ: "Asia/Taipei"
    volumes:
      - ./backend:/app
    ports:
      - "8002:8000"
    depends_on:
      - db
    networks:
      - internal
  vue:
    build:
      context: .
      dockerfile: docker/FrontendDockerfile
    container_name: django-vue-frontend
    volumes:
      - .:/app
    ports:
      - "8082:8080"
    depends_on:
      - django
    networks:
      - internal
networks:
  internal:
    driver: bridge