# Generated by Django 4.1.2 on 2023-09-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_forestinfo_adminname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestinfo',
            name='AdminName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forestinfo',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forestinfo',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forestinfo',
            name='OpenText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestinfo',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='forestinfo',
            name='RegionID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestinfo',
            name='RegionID1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestinfo',
            name='TypID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestinfo',
            name='TypName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
