[tool.poetry]
name = "django-project"
version = "0.1.0"
description = ""
authors = ["frances <n1096804@ntub.edu.tw>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
